name: 'test setup-helm action'

on:
  push:
    branches: [main]

jobs:
  asserts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: 'run action'
        uses: ./

      - name: 'assert helm is installed'
        run: helm version
          
      - name: 'assert installed version matches requested version'
        shell: bash
        run: '[ "$(helm version --template "{{ .Version }}")" = "${HELM_VERSION}" ]'
